Enable S3 compatible storage
FriendsOfFlarum/upload pull request #238
Opened 2020-09-08 14:51 UTC by AndreasSko

Adding `endpoint`, `use_path_style_endpoint`, and `ACL` to the S3 settings (titled as "advanced"). This allows to use S3 compatible storage like Backblaze B2 (solving https://github.com/FriendsOfFlarum/upload/issues/164).

The AWS SDK for PHP sets the ACL to `private` as default, which some providers don't support if the bucket policy is set to something else. Therefore the `awsS3ACL` setting allows to tweak that.

I tested the change with AWS S3 and Backblaze B2. I'm open for suggestions and comments 😊

2020-09-10 09:01 UTC, luceos approved these changes

2020-09-13 20:16 UTC, clarkwinkelmann requested changes

2020-09-13 20:16 UTC, clarkwinkelmann commented on src/Adapters/Flysystem.php
> -        $meta = $this->adapter->{$method}($file->path, $contents, new Config());
Should we add a new overridable method to `Adapters/Flysystem` so that this can be moved to `Adapters/AwsS3` instead? It doesn't seem super logical to have s3-specific stuff in the abstract flysystem adapter.

2020-09-13 20:16 UTC, clarkwinkelmann commented on src/Adapters/Flysystem.php
> +        if (!empty($settings->get('awsS3ACL'))) {
In the interest of saving up SQL requests, I'd recommend using a syntax like

```
if ($acl = $settings->get('awsS3ACL')) {
    $config->set('ACL', $acl);
}
```

Because I believe each time we call `get` on the settings object, a new database query is made.

This would also apply to the other changes in `StorageServiceProvider` but there we should reformat all existing calls as well to take this into account, so that would be for another PR I guess...

2020-09-14 07:20 UTC, luceos commented on src/Adapters/Flysystem.php
> -        $meta = $this->adapter->{$method}($file->path, $contents, new Config());
🤔 good point. The aws related settings should not be contained inside the Flysystem abstract, but in the AWS driver.

2020-09-14 08:34 UTC, AndreasSko commented on src/Adapters/Flysystem.php
> -        $meta = $this->adapter->{$method}($file->path, $contents, new Config());
Yeah, that makes sense. I changed it to use a `getConfig()` function, which the AwsS3 class overwrites. What do you think?

2020-09-14 08:35 UTC, AndreasSko commented on src/Adapters/Flysystem.php
> +        if (!empty($settings->get('awsS3ACL'))) {
Oh, good point - thanks! Updated it to your recommendation :)

2020-09-14 08:56 UTC, luceos commented on src/Adapters/Flysystem.php
> -        $meta = $this->adapter->{$method}($file->path, $contents, new Config());
Excellent work Andreas 👍

2020-09-27 20:41 UTC, clarkwinkelmann commented
Sorry for the delay. I'm hoping to try out the PR the coming week and I can take care of the merge at this time.

Or if someone else from FoF wants to beat me to it, feel free...

2020-12-03 09:46 UTC, karaok491 requested changes
Thank you for your work on this @AndreasSko 

Could I please ask you to rebase from `master` to give this PR a bit of a refresh? You'll also need to re-work your changes in `StorageServiceProvider.php` in light of some of the other recent changes to this extension.

Final thing, please don't commit the `dist` folder contents, we'll take care of that during the merge to `master`

Subject to a final local test of this PR, I'll happily merge this into master once these changes have been made. Great job!

2020-12-03 09:46 UTC, karaok491 commented on js/src/admin/components/UploadPage.js
> +                                oninput: m.withAttr('value', this.values.awsS3ACL),
`m.withAttr` should now be `withAttr`, in light of the Mithril 2 changes

2020-12-03 09:46 UTC, karaok491 commented on js/src/admin/components/UploadPage.js
> +                                oninput: m.withAttr('value', this.values.awsS3Endpoint),
`m.withAttr` should now be `withAttr`, in light of the Mithril 2 changes

2020-12-06 16:36 UTC, imorland commented
Sorry if this jumps the gun, but I needed S3 alt for a project, so based a new PR (#251 ) and merged.

Thank you for your efforts @AndreasSko

2020-12-06 16:36 UTC, closed without merging