feat: add support for text file preview embeds
FriendsOfFlarum/upload pull request #303
Opened 2021-12-07 00:25 UTC by davwheat

**Changes proposed in this pull request:**

- Adds a new text file preview upload template.

**Reviewers should focus on:**

Does this scale for large communities, since the file is loaded in JS? Somehow injecting the initial snippet in the template seems like a better idea, but I've no idea how that can be done.

**Screenshot**

![image](https://user-images.githubusercontent.com/7406822/144943269-0cb02c57-db1b-4543-915b-45b0125c8685.png)

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

2021-12-09 13:29 UTC, clarkwinkelmann requested changes
Nice feature! Definitely something we'd want supported.

However as you say I'm not too sure about the implementation. Storing the preview in TextFormatter XML would be ideal. I *think* it could be done with TextFormatter hooks without having to change our templates API, but I'm not entirely sure.

I have not been able to test locally yet, but I have already added a few observations based on the code.

Most important of which is whether users can provide an arbitrary URL that will then be fetched by Flarum without any additional checks.

2021-12-09 13:29 UTC, clarkwinkelmann commented on resources/locale/en.yml
> +        mime_types: "Configure your mime type, upload adapter mapping"
I'm not against this change, but I'm curious why it was changed in this PR? Was it done automatically by some software?

2021-12-09 13:29 UTC, clarkwinkelmann commented on resources/templates/text-preview.blade.php
> +            @php echo($translator->trans('fof-upload.ref.text_preview.expand')); @endphp
I think `ref` is supposed to be a namespace only to be referenced from other translations. I'd prefer we use a different namespace.

I don't think there's a standard name for textformatter namespace. Mentions seems to use `forum` https://github.com/flarum/mentions/blob/85b4f3abdbf8e1cfcece6b51a54071616ba06d69/locale/en.yml#L50

2021-12-09 13:29 UTC, clarkwinkelmann commented on resources/templates/text-preview.blade.php
> +            fetch('{@url}')
Why not use `app.request()` to stay consistent with other parts of the code and Flarum itself?

2021-12-09 13:29 UTC, clarkwinkelmann commented on resources/templates/text-preview.blade.php
> +</figure>
No newline at the end of file. Don't our editorconfig enforces it?

2021-12-09 13:29 UTC, clarkwinkelmann commented on resources/templates/text-preview.blade.php
> +                    figure.setAttribute('data-loading', 'false');
Is there a difference with `figure.dataset.loading = 'false'` ? Probably doesn't really matter, but the syntax I'm used to is shorter :innocent:

2021-12-09 13:31 UTC, clarkwinkelmann commented on resources/templates/text-preview.blade.php
> +            fetch('{@url}')
I thought I had made a separate conversation about the arbitrary URL thing I mention in the review comment, but apparently not. But basically it's here. Can't the user provide any URL they want and we fetch it here without any additional check?

2021-12-09 14:12 UTC, davwheat commented on resources/templates/text-preview.blade.php
> +            fetch('{@url}')
The fetch API is generally more performant, since app.request uses XMLHttpRequest under the hood.

fetch is supported by all browsers that Flarum supports, and it makes for simpler code within the template.

2021-12-09 14:12 UTC, davwheat commented on resources/templates/text-preview.blade.php
> +            fetch('{@url}')
Re the arbitrary fetching, yes it absolutely does.

This is no different to being able to put any URL inside an image tag in bbcode or markdown, though.

2021-12-09 14:14 UTC, davwheat commented on resources/templates/text-preview.blade.php
> +                    figure.setAttribute('data-loading', 'false');
No difference, except dataset is slightly slower in performance tests. I'm more used to this as a result. I don't mind changing it, though.

2021-12-09 14:14 UTC, davwheat commented on resources/locale/en.yml
> +        mime_types: "Configure your mime type, upload adapter mapping"
Yeah, done by Prettier. 😛

2021-12-10 12:54 UTC, davwheat commented
@clarkwinkelmann Still got the other things to work on but after hours of pain, I've got the snippet saving in the XML now!

2021-12-11 00:12 UTC, imorland requested changes
Just a quick glance over, I'll run this locally in the morning.

Really like how this is looking, it'll be a big win once it's released 👍

2021-12-11 00:12 UTC, imorland commented on resources/less/forum/textPreview.less
> +    // }
If this is surplus, let's remove it ;)

2021-12-11 00:12 UTC, imorland commented on src/Formatter/TextPreview/FormatTextPreview.php
> +     * Configure rendering for user mentions.
mentions?

2021-12-11 01:55 UTC, davwheat commented on src/Formatter/TextPreview/FormatTextPreview.php
> +     * Configure rendering for user mentions.
Definitely not a copy-paste 🙈

2021-12-11 01:56 UTC, davwheat commented on src/Formatter/TextPreview/FormatTextPreview.php
> +     * Configure rendering for user mentions.
```suggestion
     * Configure rendering for text preview uploads.
```

2021-12-11 01:56 UTC, davwheat commented on resources/less/forum/textPreview.less
> +    // }
```suggestion
```

2021-12-11 13:23 UTC, davwheat commented
I'm going to need to somehow include the post ID in the formatted view, because otherwise sometimes the URL it attempts to fetch contains `undefined`.

2022-01-25 13:46 UTC, imorland approved these changes

2022-01-25 13:47 UTC, merged